# GitHub Pages configuration for Vitality Dose
# https://vitalitydose.in

title: "Vitality Dose"
description: "Science-backed nutrition coaching in Bangalore, Karnataka & Guruzala, Palnadu, Andhra Pradesh Physycially and Pan India Virtually"
url: "https://vitalitydose.in"
baseurl: ""

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: "Niranjan Damodar— Vitality Dose"
twitter:
  username: vitalitydose
social:
  name: Vitality Dose
  links:
    - https://www.instagram.com/vitalitydose.in
    - https://www.youtube.com/@VitalityDose.in.99
    - https://www.linkedin.com/company/vitalitydose/
    - https://x.com/vitalitydose99

# Exclude build artifacts
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
